hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("waybar")
    hl.exec_cmd("cliphist")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("swaync")
    hl.exec_cmd("steam")
    hl.exec_cmd("openrgb -p 'romulus.orp'")
    hl.exec_cmd("systemctl --user enable opentabletdriver.service --now")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("kdeconnectd")
end)
