-- Generated by Matugen
local M = {}

M = {
    primary = "rgb(cdbdff)",
    on_primary = "rgb(34275e)",
    primary_container = "rgb(4b3e76)",
    on_primary_container = "rgb(e8deff)",
    secondary = "rgb(cbc3dc)",
    on_secondary = "rgb(322e41)",
    secondary_container = "rgb(494458)",
    on_secondary_container = "rgb(e7def8)",
    tertiary = "rgb(eeb8ca)",
    on_tertiary = "rgb(492533)",
    tertiary_container = "rgb(633b4a)",
    on_tertiary_container = "rgb(ffd9e4)",
    error = "rgb(ffb4ab)",
    on_error = "rgb(690005)",
    error_container = "rgb(93000a)",
    on_error_container = "rgb(ffdad6)",
    background = "rgb(141318)",
    on_background = "rgb(e6e1e9)",
    surface = "rgb(141318)",
    on_surface = "rgb(e6e1e9)",
    surface_variant = "rgb(48454e)",
    on_surface_variant = "rgb(cac4cf)",
    outline = "rgb(938f99)",
    shadow = "rgb(000000)",
}

return M
