-- Generated by Matugen
local M = {}

M = {
    primary = "#cdbdff",
    on_primary = "#34275e",
    primary_container = "#4b3e76",
    on_primary_container = "#e8deff",
    secondary = "#cbc3dc",
    on_secondary = "#322e41",
    secondary_container = "#494458",
    on_secondary_container = "#e7def8",
    tertiary = "#eeb8ca",
    on_tertiary = "#492533",
    tertiary_container = "#633b4a",
    on_tertiary_container = "#ffd9e4",
    error = "#ffb4ab",
    on_error = "#690005",
    error_container = "#93000a",
    on_error_container = "#ffdad6",
    background = "#141318",
    on_background = "#e6e1e9",
    surface = "#141318",
    on_surface = "#e6e1e9",
    surface_variant = "#48454e",
    on_surface_variant = "#cac4cf",
    outline = "#938f99",
    shadow = "#000000",
}

return M
