-- Generated by Matugen
local M = {}

M = {
    primary = "rgb(ffb4a3)",
    on_primary = "rgb(561f12)",
    primary_container = "rgb(733426)",
    on_primary_container = "rgb(ffdad2)",
    secondary = "rgb(e7bdb4)",
    on_secondary = "rgb(442a23)",
    secondary_container = "rgb(5d3f39)",
    on_secondary_container = "rgb(ffdad2)",
    tertiary = "rgb(dbc58c)",
    on_tertiary = "rgb(3c2f04)",
    tertiary_container = "rgb(544519)",
    on_tertiary_container = "rgb(f8e1a6)",
    error = "rgb(ffb4ab)",
    on_error = "rgb(690005)",
    error_container = "rgb(93000a)",
    on_error_container = "rgb(ffdad6)",
    background = "rgb(1a110f)",
    on_background = "rgb(f1dfdb)",
    surface = "rgb(1a110f)",
    on_surface = "rgb(f1dfdb)",
    surface_variant = "rgb(534340)",
    on_surface_variant = "rgb(d8c2bd)",
    outline = "rgb(a08c88)",
    shadow = "rgb(000000)",
}

return M
